# Generated by Django 4.2.11 on 2026-04-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_socialquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundaySchoolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_school_enrollments', to='api.member')),
                ('sunday_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.sundayschool')),
            ],
            options={
                'db_table': 'sunday_school_members',
                'unique_together': {('sunday_school_class', 'member')},
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('present_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sunday_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.sundayschool')),
            ],
            options={
                'db_table': 'sunday_school_attendance',
                'ordering': ['-date'],
                'unique_together': {('sunday_school_class', 'date')},
            },
        ),
    ]
