# Generated by Django 4.2.11 on 2026-04-17 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('Faith', 'Faith'), ('Prayer', 'Prayer'), ('Love', 'Love'), ('Hope', 'Hope'), ('Worship', 'Worship'), ('Grace', 'Grace'), ('Strength', 'Strength'), ('Healing', 'Healing'), ('Salvation', 'Salvation'), ('Peace', 'Peace')], max_length=50)),
                ('quote_text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_quotes',
                'ordering': ['-usage_count', '?'],
                'indexes': [models.Index(fields=['theme', 'is_active'], name='social_quot_theme_6fc73d_idx'), models.Index(fields=['usage_count'], name='social_quot_usage_c_782d75_idx')],
            },
        ),
    ]
