# Generated by Django 4.2.11 on 2026-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sundayschoolmember_sundayschoolattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayschool',
            name='age_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sundayschool',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
