# Generated by Django 4.2.11 on 2026-04-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_login_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='api.branch'),
        ),
    ]
