# Generated by Django 4.2.11 on 2026-04-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_prayerrequest_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_bishop_broadcast',
            field=models.BooleanField(default=False, help_text='If True, visible to all branch admins/secretaries'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='api.branch'),
        ),
    ]
